// Exercise 26:
export const ADD_STEP = "ADD_STEP"
export const REMOVE_STEP = "REMOVE_STEP"
export const UPDATE_STEP = "UPDATE_STEP"

// Exercise 27:
export const ADD_ITEM = "ADD_ITEM"
export const REMOVE_ITEM = "REMOVE_ITEM"
export const UPDATE_ITEM = "UPDATE_ITEM"

// Exercise 27 Extra:
export const ADD_SHOPPING_LIST = "ADD_SHOPPING_LIST"
export const REMOVE_SHOPPING_LIST = "REMOVE_SHOPPING_LIST"
export const UPDATE_SHOPPING_LIST = "UPDATE_SHOPPING_LIST"
export const ADD_ITEM_TO_SHOPPING_LIST = "ADD_ITEM_TO_SHOPPING_LIST"
export const REMOVE_ITEM_FROM_SHOPPING_LIST = "REMOVE_ITEM_FROM_SHOPPING_LIST"
export const UPDATE_ITEM_FROM_SHOPPING_LIST = "UPDATE_ITEM_FROM_SHOPPING_LIST"

// Exercise 28:
export const SAVE_USER = "SAVE_USER"
export const UPDATE_USER = "UPDATE_USER"